# Generated by Django 4.1.7 on 2023-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
    ]
