# Generated by Django 4.1.7 on 2023-04-10 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absusr', '0002_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Contracts'), ('2', 'Trust'), ('3', 'Deeds'), ('4', 'Common loan Documents'), ('5', 'Affidavits'), ('6', 'Vehicle certificate of ownership'), ('7', 'Acknowledgement'), ('8', 'Identity verifications')], default='1', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('Address_line1', models.CharField(max_length=255)),
                ('Address_line2', models.CharField(max_length=255)),
                ('notary_method', models.CharField(choices=[('1', 'online'), ('2', 'offline')], default=None, max_length=255)),
                ('documentupload_method', models.CharField(choices=[('1', 'Pickup'), ('2', 'Download from app')], default='2', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notary_agent_name', models.CharField(default=None, max_length=255)),
                ('service_name', models.CharField(default=None, max_length=255)),
                ('Notary_agent_charges', models.IntegerField(default=None)),
                ('Customer_name', models.CharField(default=None, max_length=255)),
                ('Commission_Number', models.CharField(default=None, max_length=15)),
                ('Delivery_charges', models.IntegerField(default=10)),
                ('Service_charges', models.IntegerField(default=20)),
                ('Total', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('1', 'Completed'), ('2', 'In Progress'), ('3', 'Cancelled'), ('4', 'Not started')], default='4', max_length=255)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
